spring.application.name=olive-kitchen
server.port=8000

#DATABASE CONFIGURATION
#SUPABASE CONFIGURATION
#spring.datasource.url=jdbc:postgresql://aws-1-ap-southeast-1.pooler.supabase.com:5432/postgres?user=postgres.cdtcbiwrqwsqvfpfmtxu&password=6p7RYtu7DBGHdGK5
#spring.datasource.username=postgres.cdtcbiwrqwsqvfpfmtxu
#spring.datasource.password=6p7RYtu7DBGHdGK5

#LOCAL CONFIGURATION
spring.datasource.url=jdbc:postgresql://localhost:5432/olive-kitchen
spring.datasource.username=postgres
spring.datasource.password=admin123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.default_schema=olive
spring.jpa.properties.hibernate.format_sql=true

spring.datasource.hikari.schema=olive
spring.datasource.hikari.data-source-properties.prepareThreshold=0
spring.datasource.hikari.data-source-properties.binaryTransfer=false